[build]
  base = "web"
  command = "npm run build"
  publish = "dist"

[build.environment]
  VITE_API_URL = "https://api.thynkdata.com"

# Proxy API endpoints to the backend
[[redirects]]
  from = "/admin/*"
  to = "https://api.thynkdata.com/admin/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/generate"
  to = "https://api.thynkdata.com/generate"
  status = 200
  force = true

[[redirects]]
  from = "/health"
  to = "https://api.thynkdata.com/health"
  status = 200
  force = true

# Keep the SPA fallback last
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 
